/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:4f03cd51-4780-4796-b9b7-11c900c059d8",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_x9Vno1oqE",
    "aws_user_pools_web_client_id": "596f3d4mahiugg8kp7iq15q099",
    "oauth": {},
    "aws_user_files_s3_bucket": "cmpe172storeappec7f744e59154260b845662bdeed7d31122509-prod",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://lm2cbfpdezbydhzqf3lvu3hp4i.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-uvavx5iiq5d5xn6erxnxgeodoa"
};


export default awsmobile;
